<?php
declare(strict_types=1);
require __DIR__ . '/lib/app.php';
$pageNonce = base64_encode(random_bytes(18));
try { web_bootstrap($pageNonce); } catch (Throwable $e) {
    http_response_code(503); header('Content-Type: text/html; charset=utf-8');
    echo '<!doctype html><html lang="de"><meta charset="utf-8"><title>Familienkalender einrichten</title><link rel="stylesheet" href="assets/style.css"><main class="page"><section class="auth-card"><div><h1>Fast bereit.</h1><p>' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8') . '</p><p>Die Einrichtung ist in der README beschrieben.</p></div></section></main></html>'; exit;
}
?><!doctype html>
<html lang="de">
<head>
<?php require __DIR__ . '/lib/page-head.php'; ?>
</head>
<body>
<a class="skip-link" href="#main">Zum Kalender</a>
<div class="page">
    <header class="site-bar">
        <a class="site-brand" href="./"><img src="assets/family.svg" width="44" height="44" alt=""><span>Familienkalender<small id="group-label">Unser gemeinsamer Kalender</small></span></a>
        <nav id="user-nav" hidden aria-label="Kalenderverwaltung"><button class="button quiet" id="members-open">Mitglieder</button><button class="button quiet" id="profile-open">Mein Konto</button><button class="button quiet" id="settings-open"><span aria-hidden="true">⚙</span> Einstellungen</button><button class="button quiet" id="logout">Abmelden</button></nav>
        <span class="private-label" id="private-label">Ein Kalender für uns alle</span>
    </header>
    <main id="main">
        <section class="hero" aria-labelledby="hero-title"><img class="hero-photo" id="hero-photo" alt="" hidden>
            <div><p class="eyebrow">DIE SCHÖNEN TAGE SIND GEMEINSAM NOCH SCHÖNER</p><h1 id="hero-title">Zusammen erinnern.<br>Mehr Freude teilen.</h1><p class="hero-description">Geburtstage, besondere Tage und ein guter Grund,<br class="desktop-break"> aneinander zu denken.</p><span class="today-pill" id="today-label">Schön, dass wir aneinander denken.</span></div>
            <div class="hero-note"><span aria-hidden="true">☀</span> Für heute.<br>Für uns.</div>
        </section>
        <p id="loading" class="loading" role="status">Dein Kalender wird geladen …</p>
        <noscript><p class="notice">Bitte JavaScript aktivieren, um deinen Kalender zu bearbeiten.</p></noscript>
        <section id="auth-panel" class="auth-card" hidden aria-labelledby="auth-title">
            <div class="auth-intro"><span class="eyebrow">EIN PLATZ FÜR EURE ERINNERUNGEN</span><h2 id="auth-title">Willkommen bei uns.</h2><p id="auth-description">Melde dich mit deinem eigenen Konto an. Die schönen Tage teilen wir uns.</p><img src="assets/family.svg" width="84" height="84" alt="Ein Kalender mit Herz"></div>
            <div><form id="auth-form">
                <label>Deine E-Mail oder Kennung<input name="identity" required maxlength="254" autocomplete="username" placeholder="z. B. mama oder deine Mailadresse"></label>
                <label id="code-label" hidden>8-stelliger Passwort-Code aus der E-Mail<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{8}" maxlength="8" placeholder="8-stelliger Passwort-Code"></label>
                <label><span id="password-label">Dein Passwort</span><input name="password" type="password" required autocomplete="current-password" id="login-password"></label>
                <label id="confirm-label" hidden>Passwort wiederholen<input name="confirmation" type="password" autocomplete="new-password"></label>
                <details id="setup-code"><summary>Erste Anmeldung auf dem Server?</summary><label>Privater Einrichtungscode<input name="setup_key" type="password" autocomplete="off"></label><p class="field-help">Den Code erhältst du von der Person, die euren Kalender eingerichtet hat.</p></details>
                <label class="check" id="remember-label"><input name="remember" type="checkbox" checked> Dauerhaft angemeldet bleiben</label>
                <p class="form-error" id="auth-error" role="alert" hidden></p><button class="button primary full" id="auth-submit" type="submit">Kalender öffnen →</button>
            </form><div class="auth-links"><button class="text-button" id="recover">Passwort vergessen?</button><button class="text-button" id="enter-code">Passwort-Code eingeben</button><button class="text-button" id="back-login" hidden>Zurück zur Anmeldung</button></div><p class="muted small" id="auth-info" role="status"></p></div>
        </section>
        <section id="welcome-panel" class="auth-card" hidden aria-labelledby="welcome-title">
            <div class="auth-intro"><span class="eyebrow">DEIN EIGENER ZUGANG</span><h2 id="welcome-title">Mach es zu deinem Kalender.</h2><p>Wähle vor dem ersten Blick in eure Termine ein persönliches Passwort. Das veröffentlichte Startpasswort wird dadurch ersetzt.</p><p id="welcome-name" class="account-badge"></p></div>
            <form id="welcome-form"><label>Bisheriges Startpasswort<input name="current_password" type="password" required autocomplete="current-password"></label><label>Dein neues Passwort<input name="new_password" type="password" minlength="10" required autocomplete="new-password"></label><label>Neues Passwort wiederholen<input name="confirmation" type="password" minlength="10" required autocomplete="new-password"></label><p class="field-help">Mindestens 10 Zeichen. Alle anderen Zugänge dieses Kontos werden abgemeldet.</p><p id="welcome-error" class="form-error" role="alert" hidden></p><button class="button primary full" type="submit">Passwort festlegen & starten</button><button class="text-button" type="button" id="welcome-logout">Mit anderem Konto anmelden</button></form>
        </section>
        <div id="calendar-app" hidden>
            <section class="upcoming-section" aria-labelledby="upcoming-title"><div class="heading-row"><h2 id="upcoming-title">Die nächsten schönen Anlässe</h2><span class="muted small" id="upcoming-subtitle">Immer etwas, worauf man sich freuen kann.</span></div><div class="upcoming-grid" id="upcoming"></div></section>
            <section class="calendar-section" aria-labelledby="list-title">
                <div class="list-heading"><div><p class="eyebrow">GUT AUFGEHOBEN</p><h2 id="list-title">Unsere Termine <span id="total-count" class="count-pill"></span></h2></div><button class="button primary" id="add-event"><span class="plus" aria-hidden="true">+</span> Neuer Termin</button></div>
                <div class="filters"><label class="search-box"><span class="sr-only">Termine durchsuchen</span><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input type="search" id="search" placeholder="Namen, Anlässe oder Notizen suchen …"></label><label><span class="sr-only">Anlass filtern</span><select id="type-filter"><option value="all">Alle Anlässe</option><option value="birthday">Geburtstage</option><option value="other">Andere Anlässe</option><option value="review">Bitte prüfen</option><option value="paused">Pausiert</option></select></label><label><span class="sr-only">Sortierung</span><select id="sort"><option value="next">Als Nächstes</option><option value="date">Im Jahreslauf</option><option value="name">Nach Name</option></select></label></div>
                <div class="month-tabs" id="months" role="group" aria-label="Nach Monat filtern"></div>
                <div class="table-wrap"><table><thead><tr><th scope="col">DATUM</th><th scope="col">NAME & ANLASS</th><th scope="col">JAHR / ALTER</th><th scope="col">NOTIZEN</th><th scope="col">ERINNERUNG</th><th scope="col"><span class="sr-only">Bearbeiten</span></th></tr></thead><tbody id="event-list"></tbody></table></div>
                <div id="empty" class="empty" hidden><span aria-hidden="true">☀</span><h3>Noch Platz für schöne Anlässe.</h3><p>Kein Termin passt zu deiner Auswahl.</p><button class="button" id="clear-filters">Filter zurücksetzen</button></div>
                <div class="list-footer"><span id="result-count" aria-live="polite"></span><a href="api.php?action=export" class="text-link" download>↓ Termine sichern</a></div>
            </section>
            <aside class="mail-strip"><span class="mail-icon" aria-hidden="true">✉</span><div><strong id="mail-summary">Eine kleine Erinnerung am Morgen.</strong><p id="mail-detail"></p></div><button class="text-button" id="mail-settings">Mail-Einstellungen <span aria-hidden="true">→</span></button></aside>
        </div>
    </main>
    <footer class="footer"><span>Ein guter Tag beginnt mit einem Gedanken aneinander. <span aria-hidden="true">☀</span></span><span>Familienkalender · Gemeinsam im Blick</span></footer>
</div>
<dialog id="event-dialog" aria-labelledby="event-title">
    <form id="event-form"><div class="dialog-header"><div><p class="eyebrow">EIN TAG ZUM MERKEN</p><h2 id="event-title">Neuer Termin</h2></div><button type="button" class="icon-button close-dialog" aria-label="Schließen">×</button></div>
        <div class="dialog-body"><input type="hidden" name="id"><label>Name / Person<input name="name" required maxlength="200" placeholder="Wer oder was ist dir wichtig?" autocomplete="off"></label>
        <div class="form-grid date-inputs"><label>Tag<input name="day" type="number" required min="1" max="31" placeholder="TT"></label><label>Monat<select name="month" id="event-month" required></select></label><label>Jahr <span class="muted">(optional)</span><input name="year" type="number" min="1" max="9999" placeholder="z. B. 1964"></label></div>
        <p class="field-help">Bei Geburtstagen das Geburtsjahr eintragen. Unbekannt? Einfach leer lassen.</p>
        <label>Anlass<input name="occasion" maxlength="160" list="occasions" placeholder="Geburtstag"><datalist id="occasions"><option value="Geburtstag"><option value="Hochzeitstag"><option value="Jahrestag"><option value="Gedenktag"><option value="Namenstag"></datalist></label>
        <div class="form-grid"><label>Wiederholung<select name="repeat"><option value="yearly">Jedes Jahr</option><option value="once">Einmalig (mit Jahr)</option></select></label><label>Zusätzlich vorher erinnern<select name="remind_before" id="remind-before"><option value="0">Nur am Tag selbst</option><option value="1">1 Tag vorher</option><option value="3">3 Tage vorher</option><option value="7">1 Woche vorher</option><option value="14">2 Wochen vorher</option><option value="30">30 Tage vorher</option></select></label></div>
        <label>Notizen<textarea name="notes" rows="3" maxlength="5000" placeholder="Geschenkidee, Telefonnummer oder ein kleiner Gedanke …"></textarea></label><p class="field-help">Notizen stehen auch in deiner Erinnerungsmail.</p>
        <label class="check"><input name="enabled" type="checkbox" checked> Erinnerung für diesen Termin aktiv</label><p id="event-warning" class="notice warning" hidden></p><p id="event-error" class="form-error" role="alert" hidden></p>
        </div><div class="dialog-footer"><button type="button" class="text-button danger" id="delete-event" hidden>Termin löschen</button><span class="spacer"></span><button type="button" class="button close-dialog">Abbrechen</button><button class="button primary" type="submit">Speichern</button></div>
    </form>
</dialog>
<dialog id="delete-dialog" aria-labelledby="delete-title"><div class="dialog-header"><h2 id="delete-title">Termin wirklich löschen?</h2><button type="button" class="icon-button close-dialog" aria-label="Schließen">×</button></div><div class="dialog-body"><p id="delete-description"></p><p class="muted">Dieser Termin wird dauerhaft aus deinem Kalender entfernt.</p><p id="delete-error" class="form-error" role="alert" hidden></p></div><div class="dialog-footer"><button type="button" class="button close-dialog">Behalten</button><button type="button" class="button destructive" id="confirm-delete">Ja, löschen</button></div></dialog>
<dialog id="settings-dialog" aria-labelledby="settings-title"><form id="settings-form"><div class="dialog-header"><div><p class="eyebrow">FÜR UNS ALLE</p><h2 id="settings-title">Kalender-Einstellungen</h2></div><button type="button" class="icon-button close-dialog" aria-label="Schließen">×</button></div>
    <div class="dialog-body"><label class="check"><input name="mail_enabled" type="checkbox"> Erinnerungsmails an alle Mitglieder aktivieren</label><div class="form-grid"><label>Zeitzone<select name="timezone"><option value="Europe/Berlin">Berlin</option><option value="Europe/Vienna">Wien</option><option value="Europe/Zurich">Zürich</option><option value="UTC">UTC</option></select></label><label>29. Februar in normalen Jahren<select name="leap_day"><option value="feb28">Am 28. Februar</option><option value="mar1">Am 1. März</option><option value="leap_only">Nur in Schaltjahren</option></select></label></div>
    <div class="settings-info"><strong>Eine Erinnerung. Für jeden von uns.</strong><p>Ein täglicher CRON-Aufruf am Morgen verschickt an jedes Mitglied eine eigene Mail mit allen fälligen Anlässen. Ohne anstehende Termine bleibt das Postfach ruhig.</p><p id="delivery-detail"></p><p id="sender-detail"></p><button type="button" class="button" id="test-mail">Testmail an mich senden</button><p id="test-mail-result" role="status" class="small"></p></div><p id="settings-error" class="form-error" role="alert" hidden></p></div><div class="dialog-footer"><button type="button" class="button close-dialog">Schließen</button><button type="submit" class="button primary">Einstellungen speichern</button></div></form></dialog>
<dialog id="profile-dialog" aria-labelledby="profile-title"><form id="profile-form"><div class="dialog-header"><div><p class="eyebrow">NUR DEIN KONTO</p><h2 id="profile-title">Mein Profil</h2></div><button type="button" class="icon-button close-dialog" aria-label="Schließen">×</button></div><div class="dialog-body"><label>Dein Name<input name="name" required maxlength="100" autocomplete="name"></label><label>Deine E-Mail-Adresse<input name="email" type="email" required autocomplete="email"></label><label>Aktuelles Passwort<input name="current_password" type="password" required autocomplete="current-password"></label><label>Neues Passwort (optional)<input name="new_password" type="password" minlength="10" autocomplete="new-password"></label><label>Neues Passwort wiederholen<input name="confirmation" type="password" autocomplete="new-password"></label><p class="field-help">Ein neues Passwort meldet nur die anderen Browser deines Kontos ab. Die Konten der anderen Mitglieder bleiben unverändert.</p><p id="profile-error" class="form-error" role="alert" hidden></p></div><div class="dialog-footer"><button type="button" class="button close-dialog">Abbrechen</button><button type="submit" class="button primary">Profil speichern</button></div></form></dialog>
<dialog id="members-dialog" aria-labelledby="members-title"><div class="dialog-header"><div><p class="eyebrow">ALLE MIT DENSELBEN RECHTEN</p><h2 id="members-title">Unsere Runde</h2></div><button type="button" class="icon-button close-dialog" aria-label="Schließen">×</button></div><div class="dialog-body"><div id="member-list"></div><form id="member-form"><h3>Ein Mitglied hinzufügen</h3><div class="form-grid"><label>Name<input name="name" required maxlength="100"></label><label>E-Mail-Adresse<input name="email" type="email" required></label></div><label>Dein Passwort zur Bestätigung<input name="current_password" type="password" required autocomplete="current-password"></label><p class="field-help">Das neue Mitglied startet mit „familienkalender“ und dem privaten Einrichtungscode. Es muss danach ein eigenes Passwort wählen. Es wird keine Einladung automatisch verschickt.</p><p id="member-error" class="form-error" role="alert" hidden></p><button type="submit" class="button primary">Mitglied hinzufügen</button></form></div><div class="dialog-footer"><button type="button" class="button close-dialog">Schließen</button></div></dialog>
<dialog id="remove-member-dialog" aria-labelledby="remove-member-title"><form id="remove-member-form"><div class="dialog-header"><h2 id="remove-member-title">Mitglied entfernen?</h2><button type="button" class="icon-button close-dialog" aria-label="Schließen">×</button></div><div class="dialog-body"><p id="remove-member-description"></p><p>Der Zugang und zukünftige Erinnerungsmails dieses Mitglieds werden beendet. Gemeinsame Termine bleiben erhalten.</p><input name="id" type="hidden"><label>Dein Passwort zur Bestätigung<input name="current_password" type="password" required autocomplete="current-password"></label><p id="remove-member-error" class="form-error" role="alert" hidden></p></div><div class="dialog-footer"><button type="button" class="button close-dialog">Behalten</button><button type="submit" class="button destructive">Mitglied entfernen</button></div></form></dialog>
<div class="toast" id="toast" role="status" hidden></div>
</body></html>
